#!/bin/bash
set -euo pipefail

# Set project root and core directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"
CORE_DIR="${PROJECT_ROOT}/src/core"

# Source core utilities
source "${CORE_DIR}/config-manager.sh" 2>/dev/null || {
    echo "Error: Failed to load ${CORE_DIR}/config-manager.sh" >&2
    exit 1
}
source "${CORE_DIR}/env-loader.sh" 2>/dev/null || {
    echo "Error: Failed to load ${CORE_DIR}/env-loader.sh" >&2
    exit 1
}
source "${CORE_DIR}/logging.sh" 2>/dev/null || {
    echo "Error: Failed to load ${CORE_DIR}/logging.sh" >&2
    exit 1
}

# Initialize environment and logging
load_environment
init_logging

log_section "PHP Configuration for Nextcloud"

# Default configuration values
readonly DEFAULT_PHP_VERSION="8.4"
readonly DEFAULT_UPLOAD_MAX_SIZE="2G"
readonly DEFAULT_MEMORY_LIMIT="512M"
readonly DEFAULT_MAX_EXECUTION_TIME=3600
readonly DEFAULT_OPCACHE_MEMORY_CONSUMPTION=256
readonly DEFAULT_OPCACHE_MAX_ACCELERATED_FILES=10000

# Load configuration
readonly PHP_VERSION=$(get_config "PHP_VERSION" "${DEFAULT_PHP_VERSION}")
readonly UPLOAD_MAX_SIZE=$(get_config "UPLOAD_MAX_SIZE" "${DEFAULT_UPLOAD_MAX_SIZE}")
readonly MEMORY_LIMIT=$(get_config "MEMORY_LIMIT" "${DEFAULT_MEMORY_LIMIT}")
readonly MAX_EXECUTION_TIME=$(get_config "MAX_EXECUTION_TIME" "${DEFAULT_MAX_EXECUTION_TIME}")

# Derived paths
readonly PHP_INI_DIR="/etc/php/${PHP_VERSION}"
readonly PHP_FPM_CONF="${PHP_INI_DIR}/fpm/php.ini"
readonly PHP_CLI_CONF="${PHP_INI_DIR}/cli/php.ini"
readonly PHP_FPM_POOL_DIR="${PHP_INI_DIR}/fpm/pool.d"
readonly PHP_FPM_POOL="${PHP_FPM_POOL_DIR}/nextcloud.conf"
readonly PHP_OPCACHE_INI="${PHP_INI_DIR}/mods-available/opcache.ini"

# Function to verify prerequisites
verify_prerequisites() {
    log_info "Verifying prerequisites..."
    
    # Check if running as root
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root"
        return 1
    fi
    
    # Verify PHP is installed
    if [ ! -f "${PHP_FPM_CONF}" ]; then
        log_error "PHP ${PHP_VERSION} is not installed. Please run install-php.sh first."
        return 1
    fi
    
    # Create backup directory
    local backup_dir="/etc/php/${PHP_VERSION}/backup-$(date +%Y%m%d%H%M%S)"
    if ! mkdir -p "${backup_dir}"; then
        log_error "Failed to create backup directory"
        return 1
    fi
    
    # Backup existing configuration
    log_info "Creating backups in ${backup_dir}"
    cp -p "${PHP_FPM_CONF}" "${backup_dir}/php-fpm.ini.bak" 2>/dev/null || true
    cp -p "${PHP_CLI_CONF}" "${backup_dir}/php-cli.ini.bak" 2>/dev/null || true
    
    if [ -f "${PHP_FPM_POOL}" ]; then
        cp -p "${PHP_FPM_POOL}" "${backup_dir}/nextcloud.conf.bak"
    fi
    
    return 0
}

# Function to set PHP configuration
set_php_config() {
    local config_file="$1"
    local config_type="$2"
    local is_fpm=false
    
    # Determine if this is an FPM configuration
    if [[ "${config_file}" == *"fpm"* ]]; then
        is_fpm=true
    fi
    
    log_info "Configuring PHP ${config_type} settings in ${config_file}..."
    
    # Create a temporary file for the new configuration
    local temp_file=$(mktemp)
    
    # Common PHP settings
    cat > "${temp_file}" << EOF
; PHP configuration for Nextcloud
; Generated on $(date)
; DO NOT EDIT THIS FILE MANUALLY - IT WILL BE OVERWRITTEN

[PHP]
; General settings
error_log = /var/log/php/php-${config_type}-error.log
log_errors = On
display_errors = Off
display_startup_errors = Off
track_errors = Off
html_errors = Off

; Resource Limits
max_execution_time = ${MAX_EXECUTION_TIME}
max_input_time = 3600
memory_limit = ${MEMORY_LIMIT}

; File Uploads
file_uploads = On
upload_max_filesize = ${UPLOAD_MAX_SIZE}
post_max_size = ${UPLOAD_MAX_SIZE}
upload_tmp_dir = /tmp
max_file_uploads = 200

; Session settings
session.save_handler = redis
session.save_path = "tcp://127.0.0.1:6379"
session.gc_maxlifetime = 3600
session.gc_probability = 1
session.gc_divisor = 1000
session.cookie_secure = 1
session.cookie_httponly = 1
session.use_strict_mode = 1
session.cookie_samesite = "Lax"

; Error handling and logging
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
log_errors_max_len = 0
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
track_errors = Off

; Security
disable_functions = exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source
disable_classes =
allow_url_fopen = Off
expose_php = Off

; Performance settings
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Zend OPcache
[opcache]
opcache.enable = 1
opcache.memory_consumption = $(get_config "OPCACHE_MEMORY" "${DEFAULT_OPCACHE_MEMORY_CONSUMPTION}")
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = $(get_config "OPCACHE_MAX_FILES" "${DEFAULT_OPCACHE_MAX_ACCELERATED_FILES}")
opcache.revalidate_freq = 1
opcache.fast_shutdown = 1
opcache.enable_cli = 1
opcache.jit = 1255
opcache.jit_buffer_size = 100M
opcache.save_comments = 1
opcache.load_comments = 1
opcache.enable_file_override = 1
opcache.validate_timestamps = 1
opcache.revalidate_path = 0
opcache.max_wasted_percentage = 5

; Only include FPM-specific settings in FPM config
$([ "$is_fpm" = true ] && echo "; PHP-FPM specific settings")
$([ "$is_fpm" = true ] && echo "[www]")
$([ "$is_fpm" = true ] && echo "; Only for FPM config")
$([ "$is_fpm" = true ] && echo "listen = /run/php/php${PHP_VERSION}-fpm.sock")
$([ "$is_fpm" = true ] && echo "listen.owner = www-data")
$([ "$is_fpm" = true ] && echo "listen.group = www-data")
$([ "$is_fpm" = true ] && echo "listen.mode = 0660")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Process manager settings")
$([ "$is_fpm" = true ] && echo "pm = dynamic")
$([ "$is_fpm" = true ] && echo "pm.max_children = $(get_config \"PHP_PM_MAX_CHILDREN\" \"50\")")
$([ "$is_fpm" = true ] && echo "pm.start_servers = $(get_config \"PHP_PM_START_SERVERS\" \"5\")")
$([ "$is_fpm" = true ] && echo "pm.min_spare_servers = $(get_config \"PHP_PM_MIN_SPARE_SERVERS\" \"5\")")
$([ "$is_fpm" = true ] && echo "pm.max_spare_servers = $(get_config \"PHP_PM_MAX_SPARE_SERVERS\" \"35\")")
$([ "$is_fpm" = true ] && echo "pm.max_requests = $(get_config \"PHP_PM_MAX_REQUESTS\" \"500\")")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Process settings")
$([ "$is_fpm" = true ] && echo "user = www-data")
$([ "$is_fpm" = true ] && echo "group = www-data")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Logging")
$([ "$is_fpm" = true ] && echo "access.log = /var/log/php/php-fpm-access.log")
$([ "$is_fpm" = true ] && echo 'access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"')
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Slow log")
$([ "$is_fpm" = true ] && echo "slowlog = /var/log/php/php-fpm-slow.log")
$([ "$is_fpm" = true ] && echo "request_slowlog_timeout = 5s")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Error log")
$([ "$is_fpm" = true ] && echo "php_flag[display_errors] = off")
$([ "$is_fpm" = true ] && echo "php_admin_value[error_log] = /var/log/php/php-fpm-error.log")
$([ "$is_fpm" = true ] && echo "php_admin_flag[log_errors] = on")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Resource limits")
$([ "$is_fpm" = true ] && echo "php_admin_value[memory_limit] = ${MEMORY_LIMIT}")
$([ "$is_fpm" = true ] && echo "php_admin_value[upload_max_filesize] = ${UPLOAD_MAX_SIZE}")
$([ "$is_fpm" = true ] && echo "php_admin_value[post_max_size] = ${UPLOAD_MAX_SIZE}")
$([ "$is_fpm" = true ] && echo "php_admin_value[max_execution_time] = ${MAX_EXECUTION_TIME}")
$([ "$is_fpm" = true ] && echo "php_admin_value[max_input_time] = 3600")
$([ "$is_fpm" = true ] && echo '')
$([ "$is_fpm" = true ] && echo "; Session settings")
$([ "$is_fpm" = true ] && echo 'php_value[session.save_handler] = redis')
$([ "$is_fpm" = true ] && echo 'php_value[session.save_path] = "tcp://127.0.0.1:6379"')
$([ "$is_fpm" = true ] && echo 'php_value[session.gc_maxlifetime] = 3600')
php_value[session.cookie_secure] = 1
php_value[session.cookie_httponly] = 1
php_value[session.use_strict_mode] = 1
php_value[session.cookie_samesite] = Lax

; Security
php_admin_flag[expose_php] = off
php_admin_flag[display_errors] = off
php_admin_value[disable_functions] = "exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source"

; Performance
php_admin_value[realpath_cache_size] = 4096K
php_admin_value[realpath_cache_ttl] = 600

; OPcache settings
php_admin_flag[opcache.enable] = 1
php_admin_value[opcache.memory_consumption] = $(get_config "OPCACHE_MEMORY" "${DEFAULT_OPCACHE_MEMORY_CONSUMPTION}")
php_admin_value[opcache.interned_strings_buffer] = 16
php_admin_value[opcache.max_accelerated_files] = $(get_config "OPCACHE_MAX_FILES" "${DEFAULT_OPCACHE_MAX_ACCELERATED_FILES}")
php_admin_value[opcache.revalidate_freq] = 1
php_admin_value[opcache.fast_shutdown] = 1
php_admin_value[opcache.enable_cli] = 1
php_admin_value[opcache.jit] = 1255
php_admin_value[opcache.jit_buffer_size] = 100M
php_admin_value[opcache.save_comments] = 1
php_admin_value[opcache.load_comments] = 1
php_admin_value[opcache.enable_file_override] = 1
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.revalidate_path] = 0
php_admin_value[opcache.max_wasted_percentage] = 5

; Environment variables
env[HOSTNAME] = \$HOSTNAME
env[PATH] = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
EOF

    # For CLI configuration, remove FPM-specific settings
    if [ "${config_type}" = "cli" ]; then
        sed -i '/^; PHP-FPM specific settings/,/^$/d' "${temp_file}"
    fi
    
    # Install the new configuration
    if ! install -m 0644 -o root -g root "${temp_file}" "${config_file}"; then
        log_error "Failed to install ${config_type} configuration"
        rm -f "${temp_file}"
        return 1
    fi
    
    rm -f "${temp_file}"
    log_info "PHP ${config_type} configuration updated successfully"
    return 0
}

# Function to configure PHP-FPM pool
configure_php_fpm_pool() {
    log_info "Configuring PHP-FPM pool for Nextcloud..."
    
    # Create PHP-FPM pool directory if it doesn't exist
    if [ ! -d "${PHP_FPM_POOL_DIR}" ]; then
        if ! mkdir -p "${PHP_FPM_POOL_DIR}"; then
            log_error "Failed to create PHP-FPM pool directory"
            return 1
        fi
    fi
    
    # Create PHP-FPM pool configuration
    cat > "${PHP_FPM_POOL}" << EOF
; Nextcloud PHP-FPM Pool Configuration
; Managed by Nextcloud setup script - DO NOT EDIT MANUALLY

[nextcloud]
user = www-data
group = www-data
listen = /run/php/php${PHP_VERSION}-fpm-nextcloud.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager configuration
pm = dynamic
pm.max_children = $(get_config "PHP_PM_MAX_CHILDREN" "50")
pm.start_servers = $(get_config "PHP_PM_START_SERVERS" "5")
pm.min_spare_servers = $(get_config "PHP_PM_MIN_SPARE_SERVERS" "5")
pm.max_spare_servers = $(get_config "PHP_PM_MAX_SPARE_SERVERS" "35")
pm.max_requests = $(get_config "PHP_PM_MAX_REQUESTS" "500")

; PHP settings
php_admin_value[memory_limit] = ${MEMORY_LIMIT}
php_admin_value[upload_max_filesize] = ${UPLOAD_MAX_SIZE}
php_admin_value[post_max_size] = ${UPLOAD_MAX_SIZE}
php_admin_value[max_execution_time] = ${MAX_EXECUTION_TIME}
php_admin_value[max_input_time] = 3600
php_admin_value[output_buffering] = 0

; OPcache settings
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.interned_strings_buffer] = 16
php_admin_value[opcache.max_accelerated_files] = 10000
php_admin_value[opcache.memory_consumption] = 256
php_admin_value[opcache.save_comments] = 1
php_admin_value[opcache.revalidate_freq] = 1
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.jit] = 1255
php_admin_value[opcache.jit_buffer_size] = 100M

; File upload settings
php_admin_value[upload_tmp_dir] = /var/www/nextcloud/tmp
php_admin_value[session.save_path] = /var/www/nextcloud/data/sessions

; Error handling
php_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php/php${PHP_VERSION}-fpm-nextcloud-error.log
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
php_admin_value[display_errors] = Off
php_admin_value[display_startup_errors] = Off
php_admin_value[log_errors_max_len] = 0

; Security
php_admin_value[expose_php] = Off
php_admin_flag[file_uploads] = On
php_admin_flag[allow_url_fopen] = Off
php_admin_flag[allow_url_include] = Off

; Session settings
php_admin_value[session.gc_maxlifetime] = 3600
php_admin_value[session.cookie_httponly] = 1
php_admin_value[session.cookie_secure] = 1
php_admin_value[session.use_strict_mode] = 1
php_admin_value[session.cookie_samesite] = Lax

; Environment variables
env[HOSTNAME] = \$HOSTNAME
env[PATH] = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
EOF

    # Set correct permissions
    chmod 0644 "${PHP_FPM_POOL}"
    log_info "PHP-FPM pool configuration created at ${PHP_FPM_POOL}"
    return 0
}

# Function to create log directory
create_log_directory() {
    local log_dir="/var/log/php"
    
    if [ ! -d "${log_dir}" ]; then
        if ! mkdir -p "${log_dir}"; then
            log_error "Failed to create log directory: ${log_dir}"
            return 1
        fi
        chown -R www-data:www-data "${log_dir}"
        chmod 0755 "${log_dir}"
    fi
    
    return 0
}

# Function to restart services
restart_services() {
    log_info "Restarting PHP-FPM service..."
    
    local php_fpm_service="php${PHP_VERSION}-fpm"
    
    if ! systemctl restart "${php_fpm_service}"; then
        log_error "Failed to restart ${php_fpm_service}"
        journalctl -u "${php_fpm_service}" -n 50 --no-pager
        return 1
    fi
    
    log_info "${php_fpm_service} restarted successfully"
    return 0
}

# Main configuration function
configure_php() {
    local success=true
    
    # Verify prerequisites
    if ! verify_prerequisites; then
        success=false
    fi
    
    # Create log directory
    if ! create_log_directory; then
        success=false
    fi
    
    # Configure PHP-FPM
    if ! set_php_config "${PHP_FPM_CONF}" "fpm"; then
        success=false
    fi
    
    # Configure PHP-CLI
    if ! set_php_config "${PHP_CLI_CONF}" "cli"; then
        success=false
    fi
    
    # Configure PHP-FPM pool
    if ! configure_php_fpm_pool; then
        success=false
    fi
    
    # Restart services
    if ! restart_services; then
        success=false
    fi
    
    # Final status
    if [ "${success}" = true ]; then
        log_success "PHP ${PHP_VERSION} configuration completed successfully"
        return 0
    else
        log_error "PHP configuration completed with errors"
        return 1
    fi
}

# Main execution
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
    
    configure_php
    exit $?
fi
cat > "/etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini" <<EOF
; Nextcloud PHP configuration
; DO NOT EDIT THIS FILE - It's managed by the configuration script

; Resource limits
memory_limit = 512M
max_execution_time = 3600
max_input_time = 3600

; File upload settings
upload_max_filesize = 2G
post_max_size = 2G
max_file_uploads = 200

; Session settings
session.save_handler = redis
session.save_path = "unix:///run/redis/redis-server.sock"
session.gc_maxlifetime = 3600
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
session.cookie_samesite = "Lax"

; OPcache settings
opcache.enable = 1
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.memory_consumption = 128
opcache.revalidate_freq = 1
opcache.validate_timestamps = 1
opcache.save_comments = 1
opcache.jit = 1255
opcache.jit_buffer_size = 50M

; Security settings
expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = On
ignore_repeated_source = Off
html_errors = Off

; Performance settings
realpath_cache_size = 512k
realpath_cache_ttl = 3600

; Additional settings
cgi.fix_pathinfo = 0
date.timezone = UTC

extension=apcu.so
extension=redis.so
EOF

# Configure PHP-FPM pool
log_info "Configuring PHP-FPM pool..."
cat > "$PHP_POOL" <<EOF
; Nextcloud PHP-FPM pool configuration
; DO NOT EDIT THIS FILE - It's managed by the configuration script

[nextcloud]
user = www-data
group = www-data
listen = /run/php/php${PHP_VERSION}-fpm-nextcloud.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager settings
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; Process settings
chdir = /
catch_workers_output = yes

; Security limits
php_admin_value[disable_functions] = exec,passthru,shell_exec,system
php_admin_flag[allow_url_fopen] = off
php_admin_flag[allow_url_include] = off

; Resource limits
php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 2G
php_admin_value[post_max_size] = 2G
php_admin_value[max_execution_time] = 3600
php_admin_value[max_input_time] = 3600

; Error handling
php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php${PHP_VERSION}-fpm-nextcloud-error.log
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
php_admin_flag[ignore_repeated_errors] = on
php_admin_flag[ignore_repeated_source] = off
php_admin_flag[html_errors] = off

; OPcache settings
php_admin_flag[opcache.enable] = on
php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.interned_strings_buffer] = 8
php_admin_value[opcache.max_accelerated_files] = 10000
php_admin_value[opcache.revalidate_freq] = 1
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.save_comments] = 1
php_admin_value[opcache.jit] = 1255
php_admin_value[opcache.jit_buffer_size] = 50M

; Session settings
php_admin_value[session.save_handler] = redis
php_admin_value[session.save_path] = "unix:///run/redis/redis-server.sock"
php_admin_value[session.gc_maxlifetime] = 3600
php_admin_value[session.cookie_lifetime] = 0
php_admin_flag[session.cookie_httponly] = 1
php_admin_flag[session.cookie_secure] = 1
php_admin_flag[session.use_strict_mode] = 1
php_admin_value[session.cookie_samesite] = "Lax"

; Environment variables
env[HOSTNAME] = \$HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
EOF

# Set proper permissions
chown -R root:www-data "$PHP_POOL_DIR"
chmod 640 "$PHP_POOL"
chmod 644 "/etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini"

# Restart PHP-FPM
log_info "Restarting PHP-FPM..."
systemctl restart "php${PHP_VERSION}-fpm"

# Verify PHP-FPM is running
if ! systemctl is-active --quiet "php${PHP_VERSION}-fpm"; then
    log_error "PHP-FPM ${PHP_VERSION} failed to start after configuration"
    journalctl -u "php${PHP_VERSION}-fpm" -n 50 --no-pager
    
    # Restore backups if available
    if [ -f "${BACKUP_DIR}/php.ini.bak" ] && [ -f "${BACKUP_DIR}/nextcloud.conf.bak" ]; then
        log_warning "Restoring original configuration from backup..."
        cp "${BACKUP_DIR}/php.ini.bak" "$PHP_INI"
        cp "${BACKUP_DIR}/nextcloud.conf.bak" "$PHP_POOL"
        systemctl restart "php${PHP_VERSION}-fpm"
    fi
    
    exit 1
fi

log_success "PHP configuration completed successfully"
log_info "PHP Version: $(php${PHP_VERSION} -r 'echo phpversion();')"
log_info "Configuration files:"
log_info "  - Main PHP config: ${PHP_INI}"
log_info "  - Nextcloud INI: /etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini"
log_info "  - PHP-FPM pool: ${PHP_POOL}"
log_info "  - Error log: /var/log/php${PHP_VERSION}-fpm-nextcloud-error.log"
