#!/bin/bash

# Load core functions and environment
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
source "$SCRIPT_DIR/core/common-functions.sh"
source "$SCRIPT_DIR/core/env-loader.sh"

# Initialize environment and logging
load_environment
init_logging

log_section "Configuring PHP for Nextcloud"

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    log_error "This script must be run as root"
    exit 1
fi

# Define PHP version
PHP_VERSION="8.4"
PHP_INI="/etc/php/${PHP_VERSION}/fpm/php.ini"
PHP_POOL_DIR="/etc/php/${PHP_VERSION}/fpm/pool.d"
PHP_POOL="${PHP_POOL_DIR}/nextcloud.conf"

# Verify PHP is installed
if [ ! -f "$PHP_INI" ]; then
    log_error "PHP ${PHP_VERSION} is not installed. Please run install-php.sh first."
    exit 1
fi

# Verify PHP-FPM pool exists
if [ ! -f "$PHP_POOL" ]; then
    log_error "PHP-FPM pool configuration not found. Run install-php.sh first."
    exit 1
fi

log_info "Optimizing PHP configuration..."

# Backup original files
BACKUP_DIR="/etc/php/${PHP_VERSION}/fpm/backup-$(date +%Y%m%d%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp "$PHP_INI" "${BACKUP_DIR}/php.ini.bak"
cp "$PHP_POOL" "${BACKUP_DIR}/nextcloud.conf.bak"
log_info "Backups saved to ${BACKUP_DIR}/"

# Configure PHP settings
log_info "Configuring PHP settings in ${PHP_INI}..."

# Base PHP configuration
cat > "/etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini" <<EOF
; Nextcloud PHP configuration
; DO NOT EDIT THIS FILE - It's managed by the configuration script

; Resource limits
memory_limit = 512M
max_execution_time = 3600
max_input_time = 3600

; File upload settings
upload_max_filesize = 2G
post_max_size = 2G
max_file_uploads = 200

; Session settings
session.save_handler = redis
session.save_path = "unix:///run/redis/redis-server.sock"
session.gc_maxlifetime = 3600
session.cookie_lifetime = 0
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
session.cookie_samesite = "Lax"

; OPcache settings
opcache.enable = 1
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.memory_consumption = 128
opcache.revalidate_freq = 1
opcache.validate_timestamps = 1
opcache.save_comments = 1
opcache.jit = 1255
opcache.jit_buffer_size = 50M

; Security settings
expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = On
ignore_repeated_source = Off
html_errors = Off

; Performance settings
realpath_cache_size = 512k
realpath_cache_ttl = 3600

; Additional settings
cgi.fix_pathinfo = 0
date.timezone = UTC

extension=apcu.so
extension=redis.so
EOF

# Configure PHP-FPM pool
log_info "Configuring PHP-FPM pool..."
cat > "$PHP_POOL" <<EOF
; Nextcloud PHP-FPM pool configuration
; DO NOT EDIT THIS FILE - It's managed by the configuration script

[nextcloud]
user = www-data
group = www-data
listen = /run/php/php${PHP_VERSION}-fpm-nextcloud.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager settings
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; Process settings
chdir = /
catch_workers_output = yes

; Security limits
php_admin_value[disable_functions] = exec,passthru,shell_exec,system
php_admin_flag[allow_url_fopen] = off
php_admin_flag[allow_url_include] = off

; Resource limits
php_admin_value[memory_limit] = 512M
php_admin_value[upload_max_filesize] = 2G
php_admin_value[post_max_size] = 2G
php_admin_value[max_execution_time] = 3600
php_admin_value[max_input_time] = 3600

; Error handling
php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php${PHP_VERSION}-fpm-nextcloud-error.log
php_admin_value[error_reporting] = E_ALL & ~E_DEPRECATED & ~E_STRICT
php_admin_flag[ignore_repeated_errors] = on
php_admin_flag[ignore_repeated_source] = off
php_admin_flag[html_errors] = off

; OPcache settings
php_admin_flag[opcache.enable] = on
php_admin_value[opcache.memory_consumption] = 128
php_admin_value[opcache.interned_strings_buffer] = 8
php_admin_value[opcache.max_accelerated_files] = 10000
php_admin_value[opcache.revalidate_freq] = 1
php_admin_value[opcache.validate_timestamps] = 1
php_admin_value[opcache.save_comments] = 1
php_admin_value[opcache.jit] = 1255
php_admin_value[opcache.jit_buffer_size] = 50M

; Session settings
php_admin_value[session.save_handler] = redis
php_admin_value[session.save_path] = "unix:///run/redis/redis-server.sock"
php_admin_value[session.gc_maxlifetime] = 3600
php_admin_value[session.cookie_lifetime] = 0
php_admin_flag[session.cookie_httponly] = 1
php_admin_flag[session.cookie_secure] = 1
php_admin_flag[session.use_strict_mode] = 1
php_admin_value[session.cookie_samesite] = "Lax"

; Environment variables
env[HOSTNAME] = \$HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
EOF

# Set proper permissions
chown -R root:www-data "$PHP_POOL_DIR"
chmod 640 "$PHP_POOL"
chmod 644 "/etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini"

# Restart PHP-FPM
log_info "Restarting PHP-FPM..."
systemctl restart "php${PHP_VERSION}-fpm"

# Verify PHP-FPM is running
if ! systemctl is-active --quiet "php${PHP_VERSION}-fpm"; then
    log_error "PHP-FPM ${PHP_VERSION} failed to start after configuration"
    journalctl -u "php${PHP_VERSION}-fpm" -n 50 --no-pager
    
    # Restore backups if available
    if [ -f "${BACKUP_DIR}/php.ini.bak" ] && [ -f "${BACKUP_DIR}/nextcloud.conf.bak" ]; then
        log_warning "Restoring original configuration from backup..."
        cp "${BACKUP_DIR}/php.ini.bak" "$PHP_INI"
        cp "${BACKUP_DIR}/nextcloud.conf.bak" "$PHP_POOL"
        systemctl restart "php${PHP_VERSION}-fpm"
    fi
    
    exit 1
fi

log_success "PHP configuration completed successfully"
log_info "PHP Version: $(php${PHP_VERSION} -r 'echo phpversion();')"
log_info "Configuration files:"
log_info "  - Main PHP config: ${PHP_INI}"
log_info "  - Nextcloud INI: /etc/php/${PHP_VERSION}/fpm/conf.d/30-nextcloud.ini"
log_info "  - PHP-FPM pool: ${PHP_POOL}"
log_info "  - Error log: /var/log/php${PHP_VERSION}-fpm-nextcloud-error.log"
